"""doc_chunks: chunk_index, text_tsv generated column, gin + hnsw indexes

Revision ID: 0276fbec8f45
Revises: 7581ef069c04
Create Date: 2026-07-09 02:08:06.278698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0276fbec8f45'
down_revision: Union[str, Sequence[str], None] = '7581ef069c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_chunks', sa.Column('chunk_index', sa.Integer(), nullable=False))
    op.add_column('doc_chunks', sa.Column('text_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', chunk_text)", persisted=True), nullable=True))
    op.create_index('ix_doc_chunks_embedding_hnsw', 'doc_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_doc_chunks_text_tsv', 'doc_chunks', ['text_tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_doc_chunks_text_tsv', table_name='doc_chunks', postgresql_using='gin')
    op.drop_index('ix_doc_chunks_embedding_hnsw', table_name='doc_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_column('doc_chunks', 'text_tsv')
    op.drop_column('doc_chunks', 'chunk_index')
    # ### end Alembic commands ###
