"""add filings.ocr_confidence

Revision ID: 7581ef069c04
Revises: ed0612ed3b38
Create Date: 2026-07-09 01:51:17.486669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7581ef069c04'
down_revision: Union[str, Sequence[str], None] = 'ed0612ed3b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filings', sa.Column('ocr_confidence', sa.Numeric(precision=3, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filings', 'ocr_confidence')
    # ### end Alembic commands ###
